"""Adicionando data_texto e data_avancada.

Revision ID: 654942bd54e9
Revises: 51a054d02de6
Create Date: 2017-01-26 14:24:44.485916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654942bd54e9'
down_revision = '51a054d02de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input', sa.Column('data_avancada', sa.DateTime(), nullable=True))
    op.add_column('input', sa.Column('data_texto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input', 'data_texto')
    op.drop_column('input', 'data_avancada')
    # ### end Alembic commands ###
